modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/TeamDman/Animus/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/TeamDman/Animus/releases"
displayURL="https://github.com/TeamDman/Animus"
logoFile="logo.png"
credits="WayOfTime for Blood Magic"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.animus]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.animus]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.animus]]
    modId="bloodmagic"
    mandatory=true
    versionRange="[3.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.animus]]
    modId="jei"
    mandatory=false
    versionRange="[15.2,)"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.animus]]
    modId="curios"
    mandatory=false
    versionRange="[5.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.animus]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.20.1-80,)"
    ordering="AFTER"
    side="BOTH"
